
shared:
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  database: lapresence_development

test:
  database: lapresence_test<%= ENV['TEST_ENV_NUMBER'] %>
