fontsize_formats: "10px,12px,14px,16px,24px,36px,48px"
plugins:
  - paste
  - image
  - link
  - fullscreen
  - anchor
  - code
  - colorpicker
  - hr
  - searchreplace
  - table
  - textcolor

toolbar: "forecolor backcolor"

paste_as_text: true
paste_word_valid_elements: true
