fontsize_formats: "10px,12px,14px,16px,24px,36px,48px"
plugins:
  - paste
  - image
  - link
  - fullscreen
  - anchor
  - code
  - colorpicker
  - hr
  - searchreplace
  - table
  - textcolor

toolbar: "forecolor backcolor fontselect fontsizeselect"

paste_as_text: true
paste_word_valid_elements: true

#font_formats: 'Arial=arial,helvetica,sans-serif;Courier New=courier new,courier,monospace;Times='

fontsize_formats: '8pt 10pt 12pt 14pt 18pt 24pt 36pt'
